name: Release tutorials (prod)

on:
  push:
    tags:
    - 'v*'

env:
  AWS_REGION: 'us-west-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@v1

    - name: S3 Sync (misc files)
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete --metadata-directive REPLACE --exclude '*.md' --cache-control max-age=0,no-cache,no-store,must-revalidate
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME_PROD }}
        SOURCE_DIR: 'content/tutorials'
        DEST_DIR: 'content/tutorials'

    - name: S3 Sync (Markdown files)
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete --metadata-directive REPLACE --exclude '*' --include '*.md' --content-type 'text/markdown' --cache-control max-age=0,no-cache,no-store,must-revalidate
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME_PROD }}
        SOURCE_DIR: 'content/tutorials'
        DEST_DIR: 'content/tutorials'

    - name: Invalidate CloudFront distribution
      uses: chetan/invalidate-cloudfront-action@v1.0
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
        PATHS: '/content/tutorials/*'

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        PURGE_URLS: '["https://www.arduino.cc/pro/"]'
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
